balancers:
  rack:
    80/http/301: https://:443/*
    443/https: https://rack:3000
services:
  rack:
    build: .
    environment:
      - DEVELOPMENT
      - FOO=bar
    test: make check test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
workflows:
  change:
    create:
      - create: staging/praxis-$branch
      - build: staging/praxis-$branch
      - test
      - promote
    close:
      - delete: staging/praxis-$branch
  merge:
    demo:
      - deploy: demo/praxis-demo
    master:
      - build: staging/praxis-staging
      - test
      - promote
      - copy: production/praxis-production
      - promote
