balancers:
  rack:
    6443/https: https://rack:3000
services:
  rack:
    build: .
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - DEVELOPMENT=false
      - PROVIDER=local
      - RACK=dev
      - VERSION
    test: make check test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/convox:/var/convox
