balancers:
  rack:
    6443/https: https://rack:3000
services:
  rack:
    build: .
    environment:
      - AWS_REGION=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - DEVELOPMENT=false
      - NAME=dev
      - PASSWORD=
      - PROVIDER=local
      - VERSION=latest
    scale: 1
    test: make test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/convox:/var/convox
