services:
  api:
    build: .
    command: bin/api
    environment:
      - PROVIDER
    ports:
      - 5000
    volumes:
      - /var/run/convox
buckets:
  builds:
    - expire: 90d
tables:
  builds:
