services:
  rack:
    build: .
    command:
      development: env DEVELOPMENT=true rerun -watch . -build github.com/convox/praxis/cmd/rack
      test: make test
    environment:
      - AWS_REGION=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - NAME=dev
      - PASSWORD=
      - PROVIDER=
      - VERSION=
    port: https:3000
    scale:
      count: 1
      memory: 256
    test: make test
    volumes:
      - /var/convox
      - /var/run/docker.sock:/var/run/docker.sock
workflows:
  change:
    create:
      - test: staging
      - create: staging/praxis-$branch
      - deploy: staging/praxis-$branch
    update:
      - test: staging
      - deploy: staging/praxis-$branch
    close:
      - delete: staging/praxis-$branch
  merge:
    demo:
      - deploy: demo/praxis-demo
    master:
      - test: staging
      - app: staging/praxis-release
      - run: bin/release
