jobs:
  build:
    docker:
      - image: convox/test
    working_directory: /go/src/github.com/convox/praxis
    steps:
      - setup_remote_docker
      - checkout
      - run: docker build -t convox/praxis:${CIRCLE_BUILD_NUM} .
      - run: go install ./cmd/cx
      - run:
          background: true
          command: cx rack start ${CIRCLE_BUILD_NUM} --frontend=none
      - run: sleep 2
      - run: docker run -it --link rack -e RACK_URL=https://rack:3000 -e PROVIDER_FRONTEND=none -e VERSION=${CIRCLE_BUILD_NUM} convox/praxis:${CIRCLE_BUILD_NUM} cx test
